[86b1vvvqu] Inventory Management - CRM
ZORI-Design/Store pull request #20
Opened 2024-08-30 01:56 UTC by wes-sleeman

# Type

`src`

# Summary

Adds inventory management functions to the CRM library and associated lambdas.

# Changes

* Added product management functions to CRM.
* Added quantity management functions to CRM.
* Added stock & catalogue querying to CRM.
* Added lambda for stock querying and quantity setting.

2024-08-30 01:56 UTC, ZoriTheDesigner commented
Task linked: [CU-86b1vvvqu Add Inventory Management to CRM](https://app.clickup.com/t/86b1vvvqu)

2024-09-01 21:00 UTC, ZoriTheDesigner requested changes

2024-09-01 21:00 UTC, ZoriTheDesigner commented on src/crm/Crm.fs
> +        genericPut "Stock" { key = key; sort = sort; data = (product, Quantity 0) }
It looks like you are bypassing the validation function `quantity`. Quantities can't be zero, we need to add another case called `OutOfStock` in our domain model.

2024-09-01 21:00 UTC, ZoriTheDesigner commented on src/crm/Crm.fs
> +    | None -> Error "Product does not exist."
We need to address the case where there is more than one product with the same name and collection name, it needs to return an error.

2024-09-01 21:00 UTC, ZoriTheDesigner commented on src/crm/Crm.fs
> +    | None -> Error "Product does not exist."
Same problem as above.

2024-09-01 21:00 UTC, ZoriTheDesigner commented on src/crm/Crm.fs
> +    | None -> Error "Product does not exist."
Same as above.

2024-09-01 21:00 UTC, ZoriTheDesigner commented on src/lambda/Stock/Function.fs
> +            | "GET" when path |> String.IsNullOrEmpty ->
Can `path` be null or empty?

2024-09-01 21:00 UTC, ZoriTheDesigner commented on src/lambda/Stock/Function.fs
> +                genericQuery<Product * Quantity> "Stock" (new QueryFilter("key", QueryOperator.Equal, path))
`path` is not product name here.

2024-09-01 21:00 UTC, ZoriTheDesigner commented on src/lambda/Stock/Function.fs
> +                    genericQuery<Product * Quantity> "Stock" (new QueryFilter("key", QueryOperator.Equal, path))
Same as above.

2024-10-04 03:58 UTC, wes-sleeman commented on src/lambda/Stock/Function.fs
> +            | "GET" when path |> String.IsNullOrEmpty ->
Change made. Now it can! :)

2024-10-08 06:26 UTC, ZoriTheDesigner reviewed
Looks good.

2024-10-08 06:33 UTC, ZoriTheDesigner approved these changes

2024-10-08 06:33 UTC, merged